services:
  vidtogallery:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    image: vidtogallery:latest
    container_name: vidtogallery-app
    restart: unless-stopped
    # Security configurations
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    
    # Temporary filesystems for writable directories
    tmpfs:
      - /tmp:noexec,nosuid,size=128m
      - /var/cache/nginx:noexec,nosuid,size=64m
      - /var/log/nginx:noexec,nosuid,size=32m
      - /var/run:noexec,nosuid,size=16m
    
    ports:
      - "80:8080"
    
    environment:
      - NODE_ENV=production
      - TZ=America/Guayaquil  # Adjust to your timezone
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Labels for management
    labels:
      - "traefik.enable=false"
      - "com.example.description=VidToGallery Vue.js App"
      - "com.example.department=frontend"
      - "com.example.label-with-empty-value"

# Networks (optional but recommended for isolation)
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

# Volumes for persistent data (if needed in the future)
volumes:
  app_logs:
    driver: local
