services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vidtogallery-frontend:latest
    volumes:
      - ../../frontend:/workspace:cached
    ports:
      - "5173:5173"
    networks:
      - vidtogallery-network
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080

networks:
  vidtogallery-network:
    external: true
    name: vidtogallery-network

volumes:
  frontend_node_modules: