  services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile
      image: vidtogallery-backend:latest
      container_name: vidtogallery-backend
      volumes:
        - ../../backend:/workspace:cached
      ports:
        - "9000:9000"
      networks:
        - vidtogallery-network
      environment:
        - GO_ENV=development
        - REDIS_URL=redis://vidtogallery-redis:6379
      depends_on:
        - redis

    redis:
      image: redis:8.0.2-alpine3.21
      container_name: vidtogallery-redis
      ports:
        - "6379:6379"
      networks:
        - vidtogallery-network
      volumes:
        - redis_data:/data
      command: redis-server --appendonly yes

  networks:
    vidtogallery-network:
      driver: bridge
      name: vidtogallery-network

  volumes:
    backend_go_cache:
    redis_data: