// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "VidToGallery API Support",
            "email": "support@vidtogallery.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/download": {
            "post": {
                "description": "Download video from social media platform with specified quality",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Video Processing"
                ],
                "summary": "Download video with quality",
                "parameters": [
                    {
                        "description": "Video URL and quality to download",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VideoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Video downloaded successfully",
                        "schema": {
                            "$ref": "#/definitions/models.VideoResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/proxy-download": {
            "post": {
                "description": "Download video file through backend proxy to avoid CORS restrictions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Video Processing"
                ],
                "summary": "Proxy download video file",
                "parameters": [
                    {
                        "description": "Video URL to proxy download",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProxyDownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Video file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/qualities": {
            "post": {
                "description": "Get list of available video qualities for a social media URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Video Processing"
                ],
                "summary": "Get available video qualities",
                "parameters": [
                    {
                        "description": "Video URL to check qualities for",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QualityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Available qualities retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/models.QualitiesResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is running and healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "API is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "models.ProxyDownloadRequest": {
            "type": "object",
            "required": [
                "video_url"
            ],
            "properties": {
                "video_url": {
                    "type": "string"
                }
            }
        },
        "models.QualitiesResponse": {
            "type": "object",
            "properties": {
                "available_qualities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.QualityOption"
                    }
                },
                "platform": {
                    "type": "string"
                }
            }
        },
        "models.QualityOption": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "quality": {
                    "type": "string"
                },
                "video_url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "models.QualityRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "models.VideoRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "quality": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.VideoResponse": {
            "type": "object",
            "properties": {
                "available_qualities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.QualityOption"
                    }
                },
                "duration": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "platform": {
                    "type": "string"
                },
                "processed_at": {
                    "type": "string"
                },
                "quality": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "video_url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "VidToGallery API",
	Description:      "API for downloading videos from social media platforms (Instagram, Twitter/X, YouTube)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
