version: '3.8'

services:
  # Redis service
  redis:
    image: redis:7-alpine
    container_name: vidtogallery-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Main application
  app:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    container_name: vidtogallery-app
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - ../.env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  default:
    name: vidtogallery-network
